export default {
  dataAreBeingUpdated: 'Data are being updated',
  login: 'Login',
  createAccount: 'Create Account',
  createNewAccount: 'Create New Account',
  email: 'Email',
  confirmEmail: 'Confirm Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  back: 'Back',
  emailError: 'Please Enter a valid Email address!',
  passwordError:
    'Passwords must be between 6 to 20 characters and contain at least one numeric digit, one uppercase and one lowercase letter!',
  retypeError: 'Re-enter is incorrect!',
  success: 'Success',
  registerSuccessPleaseLogin: 'Registered successfully, please login!',
  logoutSuccess: 'Successfully Logged Out',
  failure: 'Failure',
  anUnknowError: 'An Unknow Error',
  ok: 'OK',
  retry: 'Retry',
  cancel: 'Cancel',
}
