export default {
  dataAreBeingUpdated: 'Dự Liệu Đang Được Cập Nhật',
  login: 'Đăng Nhập',
  createAccount: 'Tạo Tài Khoản',
  createNewAccount: 'Tạo Tài Khoản Mới',
  email: 'Email',
  confirmEmail: 'Nhập lại Email',
  password: 'Mật Khẩu',
  confirmPassword: 'Nhập lại Mật Khẩu',
  back: 'Trở Lại',
  emailError: 'Vui lòng nhập chính xác email!',
  passwordError:
    'Password phải từ 6 tới 20 ký tự và chứa ít nhất một số, một từ viết hoa và một từ viết thuờng!',
  retypeError: 'Nhập lại chưa chính xác!',
  success: 'Thành Công',
  registerSuccessPleaseLogin: 'Đăng Ký Thánh Công, Vui Lòng Đăng Nhập!',
  logoutSuccess: 'Đã Đăng Xuất Thành Công',
  failure: 'Thất Bại',
  anUnknowError: 'Lỗi Không Xác Định',
  ok: 'Đồng Ý',
  retry: 'Thử Lại',
  cancel: 'Hủy',
}
